services:
  camel-router:
    image: seguros/camel-router:1.0.0
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: camel-router
    environment:
      QUARKUS_PROFILE: prod
      CAMEL_COMPONENT_KAFKA_BROKERS: seguros-kafka:29092
      # Adicione esta linha abaixo para satisfazer o placeholder {{kafka.bootstrap.servers}}:
      KAFKA_BOOTSTRAP_SERVERS: seguros-kafka:29092
      QUARKUS_KAFKA_DEVSERVICES_ENABLED: "false"
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://seguros-db:5432/seguros_db
    ports:
      - "8081:8081"
    networks:
      - seguros-network

networks:
  seguros-network:
    external: true
    name: seguros-network # ou code-with-quarkus-sinistro_seguros-network