quarkus.rest-client.camel-router.url=http://camel-router:8081
# ==========================================
# CONFIGURAÇÃO DATASOURCE (PostgreSQL)
# ==========================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:quarkus}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:quarkus}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/seguros_db}

# ==========================================
# CONFIGURAÇÃO HTTP / DEV MODE
# ==========================================
quarkus.http.port=8081
camel.route.reprocessamento-route.auto-startup=false

# Client REST do Camel Router
quarkus.rest-client.camelo-router.url=http://localhost:8081
quarkus.rest-client.camelo-router.connect-timeout=5000
quarkus.rest-client.camelo-router.read-timeout=10000

# ==========================================
# CONFIGURAÇÃO KAFKA
# ==========================================
camel.component.kafka.brokers=${CAMEL_COMPONENT_KAFKA_BROKERS:localhost:9092}
kafka.bootstrap.servers=${camel.component.kafka.brokers:localhost:9092}
quarkus.kafka.devservices.enabled=false