# ==========================================
# CONFIGURAÇÃO HTTP / DEV MODE
# ==========================================
quarkus.http.port=8081
camel.route.reprocessamento-route.auto-startup=false

# Client REST do Camel Router
quarkus.rest-client.camelo-router.url=http://localhost:8081
quarkus.rest-client.camelo-router.connect-timeout=5000
quarkus.rest-client.camelo-router.read-timeout=10000

# ==========================================
# CONFIGURAÇÃO KAFKA
# ==========================================
# Fora do container (Dev local): usa localhost:9092 (ou localhost:29092)
# Dentro do container Docker: a var CAMEL_COMPONENT_KAFKA_BROKERS sobrescreve para kafka:29092
camel.component.kafka.brokers=${CAMEL_COMPONENT_KAFKA_BROKERS:localhost:9092}
kafka.bootstrap.servers=${camel.component.kafka.brokers:localhost:9092}
# Desativa o Dev Services do Quarkus Kafka
quarkus.kafka.devservices.enabled=false
